# 1. 평균 대여 기간 >= 7일
# 2. 자동차_id, 평균대여기간(소수점, 1)
# 3. order by 평균 대여 기간 desc, 자동차_id desc
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC