# 1. 조회수가 가장 높은 게시글의 파일 경로
# 2. order by file_id DESC
# 3. /home/grep/src/게시글ID/파일ID+파일이름+파일확장자

# 불필요한 조인문 발생
# SELECT CONCAT("/home/grep/src/", B.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
# FROM USED_GOODS_BOARD B JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
# WHERE B.BOARD_ID = (
#     SELECT BOARD_ID FROM USED_GOODS_BOARD
#     ORDER BY VIEWS DESC
#     LIMIT 1
# )
# ORDER BY F.FILE_ID DESC

SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS UGB, USED_GOODS_FILE AS UGF
WHERE UGB.BOARD_ID = UGF.BOARD_ID AND
    UGB.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_PATH DESC
